(function attachUiDomElements(root: UiRoot) {
  function createDomElements(doc: Document = root.document as Document): UiDomElements {
    return {
      windowTitlebar: doc.querySelector('#windowTitlebar'),
      windowMinimizeButton: doc.querySelector('#windowMinimizeButton'),
      windowMaximizeButton: doc.querySelector('#windowMaximizeButton'),
      windowCloseButton: doc.querySelector('#windowCloseButton'),
      refreshButton: doc.querySelector('#refreshButton'),
      collectRiotMatchesButton: doc.querySelector('#collectRiotMatchesButton'),
      matchDataMenuButton: doc.querySelector('#matchDataMenuButton'),
      matchDataMenu: doc.querySelector('#matchDataMenu'),
      collectSeasonRiotMatchesButton: doc.querySelector('#collectSeasonRiotMatchesButton'),
      matchDataCount: doc.querySelector('#matchDataCount'),
      matchDataRange: doc.querySelector('#matchDataRange'),
      matchDataSeasonHint: doc.querySelector('#matchDataSeasonHint'),
      matchDataProgress: doc.querySelector('#matchDataProgress'),
      tabButtons: doc.querySelectorAll('.tab-button'),
      draftTabButton: doc.querySelector('#draftTabButton'),
      draftView: doc.querySelector('#draftView'),
      championPoolView: doc.querySelector('#championPoolView'),
      championsView: doc.querySelector('#championsView'),
      statsView: doc.querySelector('#statsView'),
      statsSubtabButtons: doc.querySelectorAll('.stats-subtab'),
      playedStatsView: doc.querySelector('#playedStatsView'),
      opponentStatsView: doc.querySelector('#opponentStatsView'),
      debugView: doc.querySelector('#debugView'),
      settingsView: doc.querySelector('#settingsView'),
      laneTabs: doc.querySelector('#laneTabs'),
      playedStatsLaneTabs: doc.querySelector('#playedStatsLaneTabs'),
      opponentStatsLaneTabs: doc.querySelector('#opponentStatsLaneTabs'),
      playedStatsSampleFilter: doc.querySelector('#playedStatsSampleFilter'),
      opponentStatsSampleFilter: doc.querySelector('#opponentStatsSampleFilter'),
      championPoolSearchInput: doc.querySelector('#championPoolSearchInput'),
      championPoolPickerGrid: doc.querySelector('#championPoolPickerGrid'),
      championPoolPickerEmpty: doc.querySelector('#championPoolPickerEmpty'),
      saveChampionPoolButton: doc.querySelector('#saveChampionPoolButton'),
      championPoolListTitle: doc.querySelector('#championPoolListTitle'),
      championPoolList: doc.querySelector('#championPoolList'),
      championPoolEmpty: doc.querySelector('#championPoolEmpty'),
      playedStatsSampleSelect: doc.querySelector('#playedStatsSampleSelect'),
      playedStatsSortGamesButton: doc.querySelector('#playedStatsSortGamesButton'),
      playedStatsSortWinRateButton: doc.querySelector('#playedStatsSortWinRateButton'),
      playedStatsTableBody: doc.querySelector('#playedStatsTableBody'),
      playedStatsEmpty: doc.querySelector('#playedStatsEmpty'),
      opponentStatsSampleSelect: doc.querySelector('#opponentStatsSampleSelect'),
      opponentStatsSortGamesButton: doc.querySelector('#opponentStatsSortGamesButton'),
      opponentStatsSortWinRateButton: doc.querySelector('#opponentStatsSortWinRateButton'),
      opponentStatsTableBody: doc.querySelector('#opponentStatsTableBody'),
      opponentStatsEmpty: doc.querySelector('#opponentStatsEmpty'),
      statsApiPatchSelect: doc.querySelector('#statsApiPatchSelect'),
      statsApiLaneSelect: doc.querySelector('#statsApiLaneSelect'),
      statsApiRankDropdownButton: doc.querySelector('#statsApiRankDropdownButton'),
      statsApiRankSummary: doc.querySelector('#statsApiRankSummary'),
      statsApiRankDropdown: doc.querySelector('#statsApiRankDropdown'),
      statsApiRankOptions: doc.querySelector('#statsApiRankOptions'),
      statsApiRefreshButton: doc.querySelector('#statsApiRefreshButton'),
      statsApiStatus: doc.querySelector('#statsApiStatus'),
      statsApiChampionsTableBody: doc.querySelector('#statsApiChampionsTableBody'),
      statsApiChampionsEmpty: doc.querySelector('#statsApiChampionsEmpty'),
      championPoolMessage: doc.querySelector('#championPoolMessage'),
      lolInstallDirInput: doc.querySelector('#lolInstallDirInput'),
      riotPlatformRegionSelect: doc.querySelector('#riotPlatformRegionSelect'),
      riotRegionalRouteStatus: doc.querySelector('#riotRegionalRouteStatus'),
      themeModeSelect: doc.querySelector('#themeModeSelect'),
      themeModeStatus: doc.querySelector('#themeModeStatus'),
      chooseLolDirButton: doc.querySelector('#chooseLolDirButton'),
      saveLolDirButton: doc.querySelector('#saveLolDirButton'),
      saveRiotPlatformRegionButton: doc.querySelector('#saveRiotPlatformRegionButton'),
      saveThemeModeButton: doc.querySelector('#saveThemeModeButton'),
      settingsMessage: doc.querySelector('#settingsMessage'),
      loggedOutView: doc.querySelector('#loggedOutView'),
      loggedInView: doc.querySelector('#loggedInView'),
      unsupportedGameModeView: doc.querySelector('#unsupportedGameModeView'),
      inGameView: doc.querySelector('#inGameView'),
      inGameSelfPortrait: doc.querySelector('#inGameSelfPortrait'),
      inGameChampionName: doc.querySelector('#inGameChampionName'),
      inGameChampionDetail: doc.querySelector('#inGameChampionDetail'),
      inGameSelfStats: doc.querySelector('#inGameSelfStats'),
      inGameLaneMatchupAnalysis: doc.querySelector('#inGameLaneMatchupAnalysis'),
      inGameFinalCompositionAnalysis: doc.querySelector('#inGameFinalCompositionAnalysis'),
      champSelectView: doc.querySelector('#champSelectView'),
      helloMessage: doc.querySelector('#helloMessage'),
      allyBans: doc.querySelector('#allyBans'),
      enemyBans: doc.querySelector('#enemyBans'),
      allyTeam: doc.querySelector('#allyTeam'),
      enemyTeam: doc.querySelector('#enemyTeam'),
      currentAction: doc.querySelector('#currentAction'),
      currentPick: doc.querySelector('#currentPick'),
      draftSelfSummary: doc.querySelector('#draftSelfSummary'),
      banInsightPanel: doc.querySelector('#banInsightPanel'),
      draftAiAnalysisPanel: doc.querySelector('#draftAiAnalysisPanel'),
      lcuStatus: doc.querySelector('#lcuStatus'),
      websocketStatus: doc.querySelector('#websocketStatus'),
      gameflowPhase: doc.querySelector('#gameflowPhase'),
      updatedAt: doc.querySelector('#updatedAt'),
      errorMessage: doc.querySelector('#errorMessage'),
      summonerJson: doc.querySelector('#summonerJson'),
      lobbyJson: doc.querySelector('#lobbyJson'),
      champSelectJson: doc.querySelector('#champSelectJson'),
      lastEventJson: doc.querySelector('#lastEventJson'),
      stateJson: doc.querySelector('#stateJson')
    };
  }

  const api: UiDomElementsApi = { createDomElements };
  if (root.document) {
    api.elements = createDomElements(root.document);
  }

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  }

  root.UiDomElements = api;
})(typeof window !== 'undefined' ? window : globalThis);
